function choose(arr) {
  let idx = Math.floor(Math.random() * arr.length);
  return arr[idx];
}

const defPrefixes = ['Agate', 'Al', 'Amber', 'Amethyst', 'Ametrine', 'Ander', 'Apple', 'Arbor', 'Ard', 'Arrow', 'Ash', 'Ashen', 'Auburn', 'Autumn', 'Back', 'Bain', 'Baldur', 'Bane', 'Baron', 'Barron', 'Barrow', 'Basalt', 'Beach', 'Bear', 'Beech', 'Bell', 'Belle', 'Beryl', 'Big', 'Birch', 'Bitter', 'Black', 'Blade', 'Blue', 'Bog', 'Bone', 'Border', 'Boulder', 'Brass', 'Break', 'Breeze', 'Briar', 'Bridge', 'Brier', 'Bright', 'Brim', 'Burn', 'Castle', 'Cedar', 'Chamber', 'Chill', 'Cinder', 'Clay', 'Cold', 'Condor', 'Corner', 'Crab', 'Crag', 'Craw', 'Crown', 'Crystal', 'Dag', 'Dark', 'Day', 'Dead', 'Deep', 'Dire', 'Dragon', 'Drake', 'Draken', 'Dread', 'Dusk', 'Eagle', 'East', 'Ebon', 'Eden', 'Edge', 'Edin', 'Elder', 'Elm', 'Ember', 'Emerald', 'Ever', 'Fae', 'Fair', 'Faire', 'Fal', 'Fall', 'Fel', 'Fell', 'Fey', 'Fir', 'Fire', 'Flint', 'Fog', 'Fort', 'Free', 'Full', 'Gay', 'Gem', 'Glow', 'Gold', 'Grand', 'Granite', 'Grass', 'Grave', 'Gray', 'Green', 'Grey', 'Griffon', 'Gryphon', 'Guild', 'Half', 'Hallow', 'Hammer', 'Hard', 'Hawk', 'Heart', 'Hearth', 'Heath', 'Hedge', 'Hem', 'High', 'Hills', 'Hollow', 'Home', 'Hope', 'Horn', 'Iron', 'Jade', 'Jasper', 'Kent', 'Key', 'King', 'Kings', 'Kirk', 'Kraig', 'Lady', 'Lake', 'Larch', 'Law', 'Leaf', 'Ledge', 'Ley', 'Lime', 'Lion', 'Little', 'Liver', 'Loch', 'Lone', 'Love', 'Low', 'Lower', 'Maiden', 'Main', 'Man', 'Mans', 'Maple', 'Marble', 'Marsh', 'Mason', 'Mass', 'May', 'Mead', 'Meadow', 'Mid', 'Middle', 'Mine', 'Mist', 'Mithril', 'Moon', 'Mord', 'Moss', 'Mourn', 'Mud', 'Murk', 'Myst', 'Mythril', 'Nettle', 'Never', 'New', 'Night', 'North', 'Oak', 'Old', 'Onyx', 'Opal', 'Pale', 'Peace', 'Pike', 'Pine', 'Plum', 'Point', 'Pond', 'Port', 'Prince', 'Pyre', 'Queen', 'Queens', 'Quiet', 'Rain', 'Rainbow', 'Ram', 'Raven', 'Red', 'Redwood', 'Rex', 'Rich', 'Ridge', 'Ring', 'River', 'Rock', 'Rose', 'Ruby', 'Rune', 'Sage', 'Sand', 'Sapphire', 'Sea', 'Sedge', 'Shade', 'Sharp', 'Sharpe', 'Shatter', 'Shaw', 'Shell', 'Shield', 'Shire', 'Shore', 'Silver', 'Skull', 'Sky', 'Slade', 'Snow', 'Sound', 'South', 'Spine', 'Spring', 'Stan', 'Star', 'Still', 'Stock', 'Stone', 'Stony', 'Storm', 'Stout', 'Strath', 'Strom', 'Summer', 'Sun', 'Sunny', 'Sword', 'Tangle', 'Teak', 'Temple', 'Timber', 'Topaz', 'Torch', 'Tower', 'Tree', 'True', 'Tumble', 'Twin', 'Tyr', 'Umber', 'Umbur', 'Under', 'Upper', 'Wake', 'Wall', 'War', 'Water', 'Way', 'Wedge', 'West', 'Wet', 'Whet', 'Whit', 'White', 'Wild', 'Will', 'Willow', 'Win', 'Wind', 'Winter', 'Wolf', 'Wood', 'Wren', 'Wyn', 'Yew'];

const defSuffixes = ['Back', 'Bank', 'Bard', 'Baron', 'Barron', 'Basin', 'Bay', 'Beach', 'Beck', 'Bell', 'Ben', 'Berg', 'Black', 'Bluff', 'Blum', 'Bog', 'Border', 'Borough', 'Bourg', 'Bourne', 'Brad', 'Brake', 'Breach', 'Breeze', 'Bridge', 'Brook', 'Burg', 'Burn', 'Bury', 'By', 'Call', 'Camp', 'Castle', 'Chester', 'City', 'Corner', 'Cott', 'Court', 'Cove', 'Crag', 'Creek', 'Crest', 'Cross', 'Crossroad', 'Crown', 'Dag', 'Dale', 'Dane', 'Dark', 'Deep', 'Del', 'Dell', 'Dike', 'Dorf', 'Drake', 'Dune', 'Edge', 'Encampment', 'End', 'Fair', 'Faire', 'Fal', 'Fall', 'Falls', 'Fast', 'Fax', 'Fel', 'Feldt', 'Fell', 'Felt', 'Field', 'Fire', 'Flint', 'Font', 'Ford', 'Forge', 'Forks', 'Forth', 'Full', 'Gard', 'Garde', 'Garden', 'Gardr', 'Gate', 'Gem', 'Gill', 'Glen', 'Glow', 'Grad', 'Grade', 'Grass', 'Grave', 'Grove', 'Guard', 'Guild', 'Hall', 'Hallow', 'Ham', 'Hamlet', 'Hand', 'Harbour', 'Haven', 'Head', 'Heart', 'Heed', 'Heim', 'Helm', 'Hill', 'Hold', 'Hollow', 'Holm', 'Holme', 'Holt', 'Home', 'Hood', 'Hope', 'Horse', 'Ington', 'Inlet', 'Island', 'Isle', 'Joy', 'Junction', 'Keep', 'Kraig', 'Lagoon', 'Lain', 'Lake', 'Land', 'Landing', 'Lands', 'Law', 'Leaf', 'Leap', 'Ledge', 'Letter', 'Light', 'Line', 'Lock', 'Lodge', 'Loft', 'Maiden', 'Mane', 'March', 'Marsh', 'Mass', 'Mead', 'Mere', 'Mesa', 'Mile', 'Mill', 'Mine', 'Mond', 'Mont', 'Moor', 'Mora', 'More', 'Morra', 'Mount', 'Mouth', 'Murk', 'Nook', 'Pad', 'Park', 'Pass', 'Path', 'Peak', 'Perch', 'Pier', 'Pike', 'Pine', 'Pines', 'Point', 'Pond', 'Pool', 'Poole', 'Port', 'Quarry', 'Quil', 'Quill', 'Quin', 'Quinn', 'Rain', 'Rapids', 'Ray', 'Reach', 'Reign', 'Rest', 'Ridge', 'Right', 'Ring', 'River', 'Rock', 'Roost', 'Rose', 'Roth', 'Rott', 'Row', 'Rowe', 'Run', 'Rune', 'Ruun', 'Sand', 'Settlement', 'Shadow', 'Sharp', 'Sharpe', 'Shaw', 'Shield', 'Shine', 'Ship', 'Shire', 'Shore', 'Side', 'Sierra', 'Sigil', 'Snow', 'Sol', 'Son', 'Sor', 'Sound', 'Spear', 'Spot', 'Square', 'Stad', 'Stain', 'Stane', 'Star', 'Station', 'Stead', 'Steppe', 'Stock', 'Ston', 'Stone', 'Stow', 'Strand', 'Strike', 'Summit', 'Sword', 'Sworth', 'Tarn', 'Tear', 'Thorn', 'Thorne', 'Thorpe', 'Throw', 'Ton', 'Tower', 'Town', 'Township', 'Trail', 'Tucket', 'Vale', 'Valley', 'Valt', 'Vanguard', 'Vault', 'Veldt', 'View', 'Village', 'Ville', 'Wake', 'Wall', 'Ward', 'Wash', 'Watch', 'Water', 'Way', 'Weald', 'Well', 'Wharf', 'Wheel', 'Wich', 'Wick', 'Wild', 'Wile', 'Will', 'Wind', 'Wing', 'Wolf', 'Wolfe', 'Wood', 'Worth', 'Wright', 'Wyn'];

const presets = new Map([
  ['Animals', ['Badger', 'Bat', 'Boar', 'Buck', 'Bull', 'Calf', 'Canary', 'Cat', 'Cattle', 'Chick', 'Chicken', 'Clam', 'Cob', 'Cock', 'Cockatiel', 'Cockatoo', 'Cockerel', 'Cockle', 'Colt', 'Cow', 'Crab', 'Crow', 'Cub', 'Deer', 'Doe', 'Dog', 'Donkey', 'Dove', 'Drake', 'Dray', 'Duck', 'Duckling', 'Ewe', 'Eyas', 'Fawn', 'Ferret', 'Foal', 'Fox', 'Frog', 'Gander', 'Gerbil', 'Goat', 'Goose', 'Gosling', 'Hamster', 'Hare', 'Hawk', 'Hedgehog', 'Hen', 'Heron', 'Horse', 'Jack', 'Jenny', 'Jill', 'Kid', 'Kingfisher', 'Kit', 'Kitten', 'Lamb', 'Leveret', 'Lobster', 'Mare', 'Mole', 'Mouse', 'Mussel', 'Nanny', 'Newt', 'Otter', 'Owl', 'Owlet', 'Oyster', 'Peachick', 'Peacock', 'Peafowl', 'Peahen', 'Pheasant', 'Pig', 'Pigeon', 'Piglet', 'Pike', 'Prickle', 'Pup', 'Puppy', 'Rabbit', 'Ram', 'Rat', 'Robin', 'Rook', 'Salmon', 'Sheep', 'Signet', 'Snail', 'Snake', 'Sneak', 'Sow', 'Sparrow', 'Spider', 'Squab', 'Squirrel', 'Stag', 'Stallion', 'Starling', 'Stoat', 'Swan', 'Tiercel', 'Toad', 'Trout', 'Vixen', 'Weasel']],
  ['Geography', ['Basin', 'Bay', 'Bluffs', 'Bush', 'Canal', 'Canyon', 'Cave', 'Cliff', 'Crag', 'Crater', 'Creek', 'Dale', 'Down', 'Falls', 'Fern', 'Flats', 'Forest', 'Fork', 'Glacier', 'Grotto', 'Heights', 'Hill', 'Hollow', 'Island', 'Knoll', 'Lagoon', 'Lake', 'Marsh', 'Mountain', 'Narrows', 'Overlook', 'Pass', 'Peak', 'Plain', 'Pond', 'Ravine', 'Reef', 'Ridge', 'River', 'Sound', 'Tree', 'Vale', 'Valley', 'Woods']],
  ['Geology', ['Agate', 'Aluminum', 'Amber', 'Amethyst', 'Basalt', 'Brass', 'Bronze', 'Chalk', 'Chrome', 'Clay', 'Coal', 'Copper', 'Coral', 'Diamond', 'Emerald', 'Feldspar', 'Flint', 'Gold', 'Granite', 'Gypsum', 'Iron', 'Jade', 'Jasper', 'Lead', 'Limestone', 'Marble', 'Mercury', 'Mica', 'Pewter', 'Platinum', 'Pyrite', 'Quartz', 'Ruby', 'Sandstone', 'Shale', 'Silt', 'Silver', 'Slate', 'Steel', 'Tin', 'Topaz']]
]);

function generate_name()
{
  let pref = choose(defPrefixes);
  let suf = choose(defSuffixes);
  return pref + suf.toLowerCase();
}